{{- if .Values.mysql.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  labels:
    app: mysql
    chart: {{ include "hospital.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: ClusterIP
  selector:
    app: mysql
  ports:
    - name: mysql
      port: {{ .Values.mysql.port }}
      targetPort: {{ .Values.mysql.port }}
      protocol: TCP
{{- end }}

{{- if .Values.backend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    app: backend
    chart: {{ include "hospital.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.backend.serviceType }}
  selector:
    app: backend
  ports:
    - name: http
      port: {{ .Values.backend.port }}
      targetPort: {{ .Values.backend.port }}
      protocol: TCP
{{- if and (eq .Values.backend.serviceType "NodePort") .Values.backend.nodePort }}
      nodePort: {{ .Values.backend.nodePort }}
{{- end }}
{{- end }}

{{- if .Values.frontend.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  labels:
    app: frontend
    chart: {{ include "hospital.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.frontend.serviceType }}
  selector:
    app: frontend
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: {{ .Values.frontend.port }}
      protocol: TCP
{{- if and (eq .Values.frontend.serviceType "NodePort") .Values.frontend.nodePort }}
      nodePort: {{ .Values.frontend.nodePort }}
{{- end }}
{{- end }}
